montezuma_actions_all = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWNRIGHT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWNLEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'UPLEFT', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UPLEFTFIRE',
    'UPLEFTFIRE', 'UPLEFTFIRE', 'UPLEFT', 'UP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'DOWNRIGHT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWNRIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
]

montezuma_actions_basic = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'FIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'FIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP'
]

montezuma_actions_basic2 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE',
    'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'NOOP', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'UP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE',
    'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP'
]

montezuma_actions_basic3 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT',
    'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP'
]

# across the room and back
# montezuma_actions_basic4 = ['NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP','DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP']

# across the room and back v2
montezuma_actions_basic4 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN',
    'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP'
]

# add dying
montezuma_actions_basic5 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN',
    'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
]

# finetune basic5
montezuma_actions_basic6 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN',
    'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'UP', 'UP', 'UP',
    'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
]

# basic5 + dying left and right
montezuma_actions_basic7 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN',
    'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + ['LEFT'] * 13 + ['NOOP'] * 2 + ['RIGHT'] * 13 + ['NOOP'] * 3 + [
    'FIRE'
] * 7 + ['NOOP'] * 2 + ['FIRE'] * 7 + ['NOOP']

montezuma_actions_basic8 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN',
    'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + ['LEFT'] * 13 + ['NOOP'] * 2 + ['RIGHT'] * 13 + ['NOOP'] * 3 + [
    'FIRE'
] * 7 + ['NOOP'] * 2 + ['FIRE'] * 7 + [
    'NOOP'
] + ['RIGHT'] * 2 + ['RIGHTFIRE'] * 7 + ['NOOP']

montezuma_actions_basic9 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN',
    'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + ['LEFT'] * 13 + ['NOOP'] * 2 + ['RIGHT'] * 13 + ['NOOP'] * 3

montezuma_actions_basic10 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN',
    'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + ['LEFT'] * 13 + ['NOOP'] * 2 + ['RIGHT'] * 13 + ['NOOP'] * 2 + [
    'LEFT'
] * 6 + ['NOOP'] * 10

# completely new
montezuma_actions_basic11 = [
    'NOOP', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT',
    'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'FIRE', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'NOOP', 'NOOP',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP',
    'UP', 'UP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'NOOP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'NOOP',
    'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP',
    'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP'
]

# completely new, and not trying to rely on symmetry, and focus on getting to the rope and dying on conveyer belt
montezuma_actions_basic12 = [
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP',
    'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'FIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'LEFT',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP',
    'UP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'NOOP', 'UP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'DOWN', 'NOOP',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN', 'DOWNRIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP',
    'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'NOOP',
    'DOWN', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'NOOP', 'NOOP',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP'
]

# like basic9 until 540 then jump to the rope many times
montezuma_actions_basic13 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT',
    'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'DOWN',
    'DOWN', 'DOWN', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'UP', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT',
    'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'NOOP', 'NOOP', 'NOOP', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'FIRE',
    'FIRE', 'FIRE', 'FIRE', 'FIRE', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'UP', 'UP', 'UP', 'UP', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'UP', 'UP',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UP', 'NOOP', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP',
    'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'NOOP', 'NOOP', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'DOWN', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP',
    'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP'
] + [
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP',
    'NOOP'
] + [
    'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + ['LEFT'] * 13 + ['NOOP'] * 2

montezuma_actions_pre = [
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'RIGHTFIRE', 'LEFT', 'LEFT', 'RIGHT', 'DOWN', 'LEFT',
    'FIRE', 'UP'
] + [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
] + [
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHTFIRE'
] + ['NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'UP', 'UP', 'UP', 'UP', 'UP'] + [
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE'
] + ['DOWN', 'DOWN'] + ['RIGHT', 'UP', 'RIGHT'] + [
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN'
] + ['LEFT'] + ['LEFT'] * 14 + ['NOOP']
montezuma_actions_see = [] + ['DOWN'] + [
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN'
] + ['LEFT', 'LEFT'] + [
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT',
    'RIGHT'
] + [
    'UP', 'RIGHTFIRE', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'UP'
] + ['DOWN', 'DOWN'] + [
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN'
] + ['LEFT'] + [
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'LEFT', 'UP'
] + ['UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP']

montezuma_actions_pomdp1 = ['NOOP'] * 2 + ['LEFT'] * 3 + ['RIGHT'] * 5 + [
    'RIGHTFIRE'
] * 2 + ['NOOP'] * 8

montezuma_actions_pomdp2 = [
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHTFIRE',
    'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'DOWNRIGHT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'UPLEFT', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP',
    'UP', 'UPLEFT', 'UPLEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'DOWNRIGHT', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',
    'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT',
    'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP',
    'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'
]


montezuma_actions_basic15 = montezuma_actions_basic9 + ['DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'UP', 'UP', 'UP', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP'] 

montezuma_actions_basic16 = montezuma_actions_basic15 + ['DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',  'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'DOWN', 'LEFT', 'RIGHT', 'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'UP', 'UP', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'NOOP'] 

montezuma_actions_basic17 = montezuma_actions_basic15 + ['DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'RIGHTFIRE', 'RIGHTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFTFIRE', 'LEFTFIRE', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN',  'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'LEFT', 'RIGHT', 'UP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'UP', 'UP', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'NOOP'] + ['DOWN'] * 8 + ['NOOP'] + ['LEFT'] * 4 + ['RIGHT'] * 4

montezuma_actions_test =  ['NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'NOOP', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWNLEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFTFIRE', 'LEFTFIRE', 'LEFTFIRE', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'DOWNRIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UP', 'UPRIGHT', 'RIGHT', 'RIGHT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'RIGHT', 'RIGHT', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHTFIRE', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'RIGHT', 'NOOP', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'LEFT', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP', 'NOOP']